Remove ref usage and upgrade to sb 6
uptick/react-keyed-file-browser pull request #142
Opened 2020-08-22 23:06 UTC by scaredcat

### Changes
- Update to storybook 6 using [this guide](https://medium.com/storybookjs/storybook-6-migration-guide-200346241bb5)
- Make use of the new [component story format](https://medium.com/storybookjs/component-story-format-66f4c32366df)
- Remove unnecessary use of refs

Fixes: #9

2020-08-25 10:26 UTC, mwfister requested changes
Thanks for the changes @scaredcat! All in all looks good, just needs the folder name change handler updated

2020-08-25 10:26 UTC, mwfister commented on src/base-folder.js
> -      this.newNameRef.focus()
There's [one final reference](https://github.com/uptick/react-keyed-file-browser/blob/85cc881e11ec6e76cdb8a0c5be0b2900745d40d4/src/base-folder.js#L74) to this `ref`, which will prevent renaming folders.

2020-08-26 02:20 UTC, scaredcat commented on src/base-folder.js
> -      this.newNameRef.focus()
oops. I've removed that `newNameRef` as well.

2020-08-26 02:31 UTC, mwfister approved these changes

2020-08-26 02:45 UTC, mwfister commented
Looks good to merge. We'll look into creating a new release soon™, ideally once the other active PRs are resolved.

2020-08-26 02:45 UTC, merged