Update dependencies
uptick/react-keyed-file-browser pull request #149
Opened 2020-09-16 16:26 UTC by harsh-tamr

Update all dependencies, and fix the onSelect behavior

2020-09-16 16:27 UTC, harsh-tamr commented
Fixes https://github.com/uptick/react-keyed-file-browser/issues/115 and also adds a story in the storybook

2020-09-17 21:59 UTC, harsh-tamr commented
@bor3ham @scaredcat @roymfibo @jlo-1

2020-09-20 17:20 UTC, jarekwg commented
Hey @harsh-tamr,

Thanks for your contribution!
We're all quite under the pump atm, but promise to take a look soon.

Cheers,

2020-09-25 03:38 UTC, mwfister requested changes
Thanks for your help improving this package 👍. The getFile change looks good, so I'll approve that in the separate PR. I have a couple of questions/suggestions for the dependency work below.

2020-09-25 03:38 UTC, mwfister commented on stories/index.js
> +x/y/z/broken.csv,1598519377165,323`
I imagine this story may have been used to help troubleshooting? I think we can roll it into the other stories. Thanks to your changes, we can update `files` to remove the explicit folder (first entry) and apply an `onSelect` to one of the stories.

```
const files = [
  {
    key: 'animals/',
    modified: addHours(new Date(), 1).getTime(),
    size: 0,
  },
  {
    key: 'animals/dog.png',
    modified: subHours(new Date(), 1).getTime(),
    size: 0,
  },
```

2020-09-25 03:38 UTC, mwfister commented on package.json
> +    "url-loader": "^4.1.0",
What is this `url-loader` being used for?

2020-09-25 03:38 UTC, mwfister commented on webpack.config.js
> +        loader: [require.resolve('style-loader'), require.resolve('css-loader'), require.resolve('sass-loader')],
I'm not too familiar with webpack intricacies, what's the idea behind this change?

2020-09-25 03:38 UTC, mwfister commented on package.json
>    "dependencies": {
These loaders have a minimum required node version, we should probably be specifying something to that effect
```suggestion
  "engines": {
    "node": ">=10.13.0",
  },
  "dependencies": {
```

2020-09-27 15:26 UTC, harsh-tamr commented on stories/index.js
> +x/y/z/broken.csv,1598519377165,323`
sounds good

2020-09-27 15:27 UTC, harsh-tamr commented on package.json
> +    "url-loader": "^4.1.0",
I think it was a transitive dependency, I'll look into it

2020-09-27 15:31 UTC, harsh-tamr commented on webpack.config.js
> +        loader: [require.resolve('style-loader'), require.resolve('css-loader'), require.resolve('sass-loader')],
https://webpack.js.org/api/module-methods/#requireresolve

I was playing around with yarn pnp and I ran into some issues https://classic.yarnpkg.com/en/docs/pnp/troubleshooting/ It's a way of future proofing. I'm not attached to it and can take it out

2020-09-28 09:08 UTC, mwfister commented on webpack.config.js
> +        loader: [require.resolve('style-loader'), require.resolve('css-loader'), require.resolve('sass-loader')],
That's fine to keep. I was curious about it, but not particularly opinionated.

2020-10-08 21:33 UTC, harsh-tamr commented
sorry got super busy, but will take a look soon

2021-01-25 17:50 UTC, dankolbman reviewed
Thanks for this PR! The deprecation of `DragDropContext` is preventing us from using the master branch in production.
I was able to get things working by using the first commit of this branch, although I had to manually build and install the package to do so.

2021-01-25 17:50 UTC, dankolbman commented on package.json
> +    "node": ">=10.13.0",
Trailing comma needs to be removed.

2021-02-05 20:58 UTC, harsh-tamr commented on package.json
> +    "node": ">=10.13.0",
resolved just now

2021-07-06 01:08 UTC, dreadera commented
Closing This PR as we have updated our dependencies.

2021-07-06 01:08 UTC, closed without merging