feat: replacing webpack with esbuild.
uptick/react-keyed-file-browser pull request #180
Opened 2021-06-06 23:28 UTC by dreadera

This PR is a continuation of the previous #178.

I have updated the build process for this library using `esbuild`. 
During this process I have made other adjustments to help with the modernisation of this application.

I have broken down each commit into a section I have worked on.

### Changelog
- Fast Build Pipeline with `esbuild`.
- Removed `webpack`.
- Typescript Support & Replacing `jsconfig` with `tsconfig`.
- Removed `babel`.
- `esm` Module support Added.
- Updated `eslint` dependencies & rules.

### Benefits
- Faster builds.
- Typescript Support.
- Smaller Bundle Size.
- Modern Library exports using `esm`

2021-06-06 23:41 UTC, uptickmetachu approved these changes

2021-06-06 23:41 UTC, uptickmetachu commented on esbuild.js
> +  plugins: [nodeExternalsPlugin()],
Looks good! The esbuild config looks relatively straight forward and compact. Love that we can get rid of babel as well. Perhaps add a comment as to why we use the node exclude package? 
It was the only part that wasn't immediately obvious for me

2021-06-07 01:12 UTC, jarekwg commented
Gonna remove myself as reviewer -- don't have anything of use to add.

Nice work though! :)

2021-06-07 02:48 UTC, dreadera commented on esbuild.js
> +  plugins: [nodeExternalsPlugin()],
It basically does the same function as `externals` option for webpack.

From the author:
_"When bundling with Esbuild for the backend by default it will try to bundle all the dependencies. However it's a good idea to not bundle all the node_modules dependencies. This plugin will scan the dependencies included in your project and will exclude them from the final bundle."_

2021-06-07 02:49 UTC, dreadera commented
No worries. Thank you for the feedback :)

2021-06-08 01:42 UTC, mwfister approved these changes
Good stuff.

[We've got another open PR](https://github.com/uptick/react-keyed-file-browser/pull/149) that might since be superseded by this recent work.

2021-06-08 02:04 UTC, mwfister requested changes
I should add, there's a nested `demo-site` that's still using webpack/babel.

Was also unable to get storybook to spin up, node-sass issues. Are you able to run it?

2021-06-08 03:54 UTC, dreadera commented
@mwfister cached `node_modules` will be the end of me haha. I have fixed it and pushed through :)

2021-06-08 06:49 UTC, mwfister approved these changes

2021-06-10 10:07 UTC, merged